on:
  push:
  pull_request:

name: check_sim_datas

jobs:
  check_sim_datas:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Fix rJava error # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
        run: sudo $(which R) CMD javareconf

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("richelbilderbeek/plinkr")
          remotes::install_github("richelbilderbeek/ormr")
          remotes::install_github("richelbilderbeek/gcaer")
        shell: Rscript {0}

      - name: Install plink
        run: plinkr::install_plinks()
        shell: Rscript {0}

      - name: Check dataset 1
        run: Rscript -e 'gcaer::check_gcae_input_filenames(gcaer::create_gcae_input_filenames(bed_filename = "inst/extdata/sim_data_1.bed", bim_filename = "inst/extdata/sim_data_1.bim", fam_filename = "inst/extdata/sim_data_1.fam", phe_filename = "inst/extdata/sim_data_1.phe", labels_filename = "inst/extdata/sim_data_1_labels.csv"))'

      - name: Recreate sim dataset 1, in 'nsphs_ml_qt/inst/extdata/'
        run: Rscript scripts_rackham/10_create_dataset_1.R

      - name: Show sim_data_1.bed
        run: cat nsphs_ml_qt/inst/extdata/sim_data_1.bim inst/extdata/sim_data_1.bim

      - name: Check sim_data_1.bed is the same, thanks to https://stackoverflow.com/a/12900693
        run: cmp --silent nsphs_ml_qt/inst/extdata/sim_data_1.bim inst/extdata/sim_data_1.bim || echo "sim_data_1.bim is different"; exit 42

      - name: Check sim_data_1.fam is the same, thanks to https://stackoverflow.com/a/12900693
        run: cmp --silent nsphs_ml_qt/inst/extdata/sim_data_1.fam inst/extdata/sim_data_1.fam || echo "sim_data_1.fam is different"; exit 42

      - name: Check sim_data_1.phe is the same, thanks to https://stackoverflow.com/a/12900693
        run: cmp --silent nsphs_ml_qt/inst/extdata/sim_data_1.phe inst/extdata/sim_data_1.phe || echo "sim_data_1.phe is different"; exit 42

      - name: Check sim_data_1_labels.csv is the same, thanks to https://stackoverflow.com/a/12900693
        run: cmp --silent nsphs_ml_qt/inst/extdata/sim_data_1_labels.csv inst/extdata/sim_data_1_labels.csv || echo "sim_data_1_labels.csv is different"; exit 42

      - name: Check sim_data_1.bed is the same, thanks to https://stackoverflow.com/a/12900693
        run: cmp --silent nsphs_ml_qt/inst/extdata/sim_data_1.bed inst/extdata/sim_data_1.bed || echo "sim_data_1.bed is different"; exit 42

