on:
  push:
  pull_request:

name: create_bianca_zip

jobs:
  create_bianca_zip:

    container:
      image: quay.io/singularity/singularity:v3.7.4
      options: --privileged

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Create starter zip
        run: ./scripts/0_create_starter_zip.sh

