on:
  push:
  pull_request:

name: run_scripts

jobs:
  run_scripts:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: eWaterCycle/setup-singularity@v7
      #  with:
      #    singularity-version: 3.8.3

      #- name: Install libcurl4-openssl-dev
      #  run: sudo apt install -qq libcurl4-openssl-dev

      #- name: Fix rJava error # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
      #  run: sudo $(which R) CMD javareconf

      #- name: Install dependencies
      #  run: |
      #    install.packages(c("remotes", "rcmdcheck"))
      #    remotes::install_github("richelbilderbeek/plinkr")
      #    remotes::install_github("richelbilderbeek/ormr")
      #    remotes::install_github("richelbilderbeek/gcaer")
      #  shell: Rscript {0}

      - name: Get the SIF
        run: |
          cd .. || exit 42
          singularity pull --arch amd64 library://richelbilderbeek/default/nsphs_ml_qt:0.4
          cd - || exit 314

      - name: Create sim dataset 1
        run: |
          cd .. || exit 42
          ./nsphs_ml_qt/scripts_local/20_start_issue_18.sh
          cd - || exit 314

