on:
  push:
  pull_request:

name: run_scripts

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Fix rJava error # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
        run: sudo $(which R) CMD javareconf

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("richelbilderbeek/plinkr")
          remotes::install_github("richelbilderbeek/ormr")
          remotes::install_github("richelbilderbeek/gcaer")
        shell: Rscript {0}

      - name: Install plink
        run: plinkr::install_plinks()
        shell: Rscript {0}

      - name: Clone GenoCAE
        run: git clone https://github.com/richelbilderbeek/GenoCAE ../GenoCAE

      - name: Create sim dataset 1
        run: cd .. ; ./nsphs_ml_qt/scripts_rackham/02_start_1.sh ; cd ..

