on:
  push:
  pull_request:

name: run_scripts

jobs:
  run_scripts:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      # From https://sylabs.io/guides/3.0/user-guide/installation.html
      - name: Install singularity
        run: |
          sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list && \
          sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9 && \
          sudo apt-get update
          sudo apt-get install -y singularity-container

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Fix rJava error # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
        run: sudo $(which R) CMD javareconf

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("richelbilderbeek/plinkr")
          remotes::install_github("richelbilderbeek/ormr")
          remotes::install_github("richelbilderbeek/gcaer")
        shell: Rscript {0}

      - name: Install gcae
        run: |
          mkdir gcae
          singularity pull --arch amd64 library://richelbilderbeek/default/gcae:0.1 
          mv *.sif gcae/gcae.sif

      - name: Install gcaer
        run: |
          mkdir gcaer
          singularity pull --arch amd64 library://richelbilderbeek/default/gcaer:0.6.3
          mv *.sif gcaer/gcaer.sif

      #- name: Install plink
      #  run: plinkr::install_plinks()
      #  shell: Rscript {0}

      - name: Clone GenoCAE
        run: git clone https://github.com/richelbilderbeek/GenoCAE ../GenoCAE

      - name: Create sim dataset 1
        run: cd .. ; ./nsphs_ml_qt/scripts_rackham/02_start_1.sh ; cd ..

